keywords = [
    "Books and Algorithms",
    "Fibonacci Sequence",
    "Big O Notation",
    "Algorithms and Numbers",
    "Basic Arithmetic",
    "Modular Arithmetic",
    "Primality Testing",
    "Cryptography",
    "Universal Hashing",
    "Divide and Conquer Algorithms",
    "Multiplication",
    "Recurrence Relations",
    "Merge Sort",
    "Median",
    "Matrix Multiplication",
    "Fast Fourier Transform",
    "Graph Decomposition",
    "Depth First Search in Graphs",
    "Strongly Connected Components in Graphs",
    "Paths in Graphs",
    "Breadth First Search",
    "Edge Length",
    "Dijkstra's Algorithm",
    "Priority Queue Implementation",
    "Shortest Paths with Negative Weight Edges",
    "Shortest Paths in Directed Acyclic Graphs",
    "Greedy Algorithms",
    "Minimum Spanning Tree",
    "Huffman Encoding",
    "Horn Formula",
    "Set Cover",
    "Dynamic Programming",
    "Shortest Paths in Directed Acyclic Graphs (Revisited)",
    "Longest Increasing Subsequence",
    "Edit Distance",
    "Knapsack Problem",
    "Matrix Chain Multiplication",
    "Shortest Paths",
    "Independent Sets in Trees",
    "Linear Programming and Reductions",
    "Introduction to Linear Programming",
    "Network Flow",
    "Bipartite Matching",
    "Duality",
    "Zero-Sum Games",
    "Simplex Algorithm",
    "Circuit Evaluation",
    "NP-Complete Problems",
    "Search Problems",
    "Reductions",
    "Dealing with NP-Complete Problems",
    "Intelligent Exhaustive Search",
    "Approximation Algorithms"
]
