keywords = [
    "Books and Algorithms",#0
    "Fibonacci Sequence",#1
    "Big O Notation",#2
    "Algorithms and Numbers",
    "Basic Arithmetic",
    "Modular Arithmetic",
    "Primality Testing",
    "Cryptography",
    "Universal Hashing",
    "Divide and Conquer Algorithm",
    "Multiplication",
    "Recursive Relations",
    "Merge Sort",
    "Median",
    "Matrix Multiplication",
    "Fast Fourier Transform",
    "Graph Decomposition",
    "Depth-First Search in Graphs",
    "Strongly Connected Components in Graphs",
    "Paths in Graphs",
    "Breadth-First Search",
    "Length of Edges",
    "Dijkstra's Algorithm",
    "Priority Queue Implementation",
    "Shortest Paths with Negative Weight Edges",
    "Shortest Paths in Directed Acyclic Graphs",
    "Greedy Algorithms",
    "Minimum Spanning Tree",
    "Huffman Coding",
    "Horn Formula",
    "Set Covering",
    "Dynamic Programming",
    "Shortest Paths in Directed Acyclic Graphs (Review)",
    "Longest Increasing Subsequence",
    "Edit Distance",
    "Knapsack Problem",
    "Matrix Chain Multiplication",
    "Shortest Paths",
    "Independent Sets in Trees",
    "Linear Programming and Reductions",
    "Introduction to Linear Programming",
    "Flows in Networks",
    "Bipartite Matching",
    "Duality",
    "Zero-Sum Games",
    "Simplex Algorithm",
    "Circuit Evaluation",
    "NP-Complete Problems",
    "Search Problems",
    "NP-Complete Problems",
    "Reductions",
    "Approaches to NP-Complete Problems",
    "Intelligent Exhaustive Search",
    "Approximation Algorithms",
]#一共53组